### ISSUE TITLE
可以再作下分类，比如Node， React， Python。。。

### ISSUE THREAD

**Issue by yanlee26** [WhiteYin/translation#3]

**Comment by WhiteYin** [comment]
嗯，目前翻译的两篇标题都很明确，所以没分类。  
现在给issues加了标签，应该直观一点了，而且可以在[标签页面](https://github.com/WhiteYin/translation/labels)点相应标签跳转。  
至于项目文件夹，可能会需要细分一下，但是考虑到有的文章讲项目实践会涉及到多个知识，无法准确划出侧重点，所以打算等翻译的文章多了再处理。
